apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullkek-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullkek-backend
  template:
    metadata:
      labels:
        app: fullkek-backend
    spec:
      containers:
      - name: backend
        image: 89.110.105.147:5000/fullkek-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: fullkek-backend
spec:
  selector:
    app: fullkek-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
