apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullkek-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullkek-frontend
  template:
    metadata:
      labels:
        app: fullkek-frontend
    spec:
      containers:
      - name: frontend
        image: 89.110.105.147:5000/fullkek-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fullkek-frontend
spec:
  selector:
    app: fullkek-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
